//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderMain()
        {
            this.OrderSubs = new HashSet<OrderSub>();
        }
    
        public int OrderMain_ID { get; set; }
        public Nullable<int> Shopkeeper_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<int> Payment_ID { get; set; }
        public string Delivery_Address { get; set; }
        public Nullable<int> Order_Date { get; set; }
        public Nullable<int> Delivery_Date { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Shopkeeper Shopkeeper { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSub> OrderSubs { get; set; }
    }
}
